export interface StatiticsData {
    row_number: number;
    Semana: string;
    "Month Short": string;
    Guardia: string;
    Fecha_inicio: string; 
    Total_dias: number;
    "Kg /tal": number;
    Avance_ejec: number;
    Prom_Eficiencia_vol: number;
    Prom_F_A: number;
    Avance_programado: number;
    "Avance (%)": number;
    "Orden mes for": number;
    Anual: number;
    Mes_Contable: string;
    "Orden mes": number;
    "CRE E1000 1x12": number;
    "CRE E3000 1x12": number;
    "CRE E5000 1x12": number;
    "E3000 1 14\"X24\"": number;
    "E5000 1 14\"X12\"": number;
    "E1000 1 14\"X24\"": number;
    "E1000 1 14\"X16\"": number;
    "E1000 \"1x7\"": number;
    "E3000 \"1x8\"": number;
    "E5000 78": number;
    "CRE Carmex \"1 x 5\"": number;
    "CRE Carmex \"1 x 8\"": number;
    "CRE Carmex \"2 x 1\"": number;
    "CRE Carmex \"2 x 40\"": number;
    "CRE Carmex \"3 x 60\"": number;
    "CRE Carmex \"4 x 50\"": number;
    "Carmex Blanca \"1X5\"": number;
    "CRE Mecha Rapida": number;
    "FANEL LARGO LP 3.60": number;
    "FANEL CORTO MS 4.0": number;
    "FANEL LARGO 4.2": number;
    "Mukinel  LP Largo 4.20": number;
    "Cordon detonante 5P": number;
  }